version: '3'

services:
#  readingisgood-app:
#    image: readingisgood
#    environment:
#      - AUTH_USERNAME=getir
#      - AUTH_PASSWORD=getir
#      - DB_USERNAME=getir
#      - DB_PASSWORD=getir
#      - DB_NAME=readingisgood
#      - DB_HOSTNAME=mongo
#      - DB_PORT=27017
#      - MONGO_INITDB_DATABASE=readingisgood
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
  mongo:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=getir
        - MONGO_INITDB_ROOT_PASSWORD=getir
        - MONGO_INITDB_DATABASE=readingisgood
  mongo-express:
    image: mongo-express:0.54.0
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=getir
        - ME_CONFIG_MONGODB_ADMINPASSWORD=getir
        - ME_CONFIG_MONGODB_AUTH_USERNAME=getir
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=getir
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
        - mongo
    ports:
      - "8081:8081"